servico: 'cobranca'

versao: 'fev2016'

layout: 'cnab240'

remessa:
  header_arquivo:
    codigo_banco:
      pos: [1,3]
      picture: '9(3)'
      default: 341
    lote_servico:
      pos: [4,7]
      picture: '9(4)'
      default: '0000'
    tipo_registro:
      pos: [8,8]
      picture: '9(1)'
      default: 0
    brancos_01:
      pos: [9,17]
      picture: 'X(9)'
      default: ''
    tipo_inscricao:
      pos: [18,18]
      picture: '9(1)'
    inscricao_numero:
      pos: [19,32]
      picture: '9(14)'
    brancos_02:
      pos: [33,52]
      picture: 'X(20)'
      default: ''
    zeros_01:
      pos: [53,53]
      picture: '9(1)'
      default: 0
    agencia:
      pos: [54,57]
      picture: '9(4)'
    brancos_03:
      pos: [58,58]
      picture: 'X(1)'
      default: ''
    zeros_02:
      pos: [59,65]
      picture: '9(7)'
      default: '0000000'
    conta_semdigito:
      pos: [66,70]
      picture: '9(5)'
    brancos_04:
      pos: [71,71]
      picture: 'X(1)'
      default: ''
    conta_digito:
      pos: [72,72]
      picture: '9(1)'
    nome_empresa:
      pos: [73,102]
      picture: 'X(30)'
    nome_banco:
      pos: [103,132]
      picture: 'X(30)'
      default: 'BANCO ITAU SA'
    brancos_05:
      pos: [133,142]
      picture: 'X(10)'
      default: ''
    codigo_arquivo:
      pos: [143,143]
      picture: '9(1)'
      default: 1
    data_geracao:
      pos: [144,151]
      picture: '9(8)'
    hora_geracao:
      pos: [152,157]
      picture: '9(6)'
    numero_sequencial:
      pos: [158,163]
      picture: '9(6)'
    versao_layout_arquivo:
      pos: [164,166]
      picture: '9(3)'
      default: '040'
    zeros_03:
      pos: [167,171]
      picture: '9(5)'
      default: '00000'
    brancos_06:
      pos: [172,225]
      picture: 'X(54)'
      default: ''
    zeros_04:
      pos: [226,228]
      picture: '9(3)'
      default: '000'
    brancos_07:
      pos: [229,240]
      picture: 'X(12)'
      default: ''

  header_lote:
    codigo_banco:
      pos: [1,3]
      picture: '9(3)'
      default: 341
    lote_servico:
      pos: [4,7]
      picture: '9(4)'
    tipo_registro:
      pos: [8,8]
      picture: '9(1)'
      default: 1
    tipo_operacao:
      pos: [9,9]
      picture: 'X(1)'
      default: 'R'
    tipo_servico:
      pos: [10,11]
      picture: '9(2)'
      default: '01'
    zeros_01:
      pos: [12,13]
      picture: '9(2)'
      default: '00'
    versao_layout_lote:
      pos: [14,16]
      picture: '9(3)'
      default: '030'
    brancos_01:
      pos: [17,17]
      picture: 'X(1)'
      default: ''
    tipo_inscricao:
      pos: [18,18]
      picture: '9(1)'
    inscricao_empresa:
      pos: [19,33]
      picture: '9(15)'
    brancos_02:
      pos: [34,53]
      picture: 'X(20)'
      default: ''
    zeros_02:
      pos: [54,54]
      picture: '9(1)'
      default: 0
    agencia:
      pos: [55,58]
      picture: '9(4)'
    brancos_03:
      pos: [59,59]
      picture: 'X(1)'
      default: ''
    zeros_03:
      pos: [60,66]
      picture: '9(7)'
      default: 0
    conta_semdigito:
      pos: [67,71]
      picture: '9(5)'
    brancos_04:
      pos: [72,72]
      picture: 'X(1)'
      default: ''  
    conta_digito:
      pos: [73,73]
      picture: '9(1)'
    nome_empresa:
      pos: [74,103]
      picture: 'X(30)'
    brancos_05:
      pos: [104,183]
      picture: 'X(80)'
      default: ''
    numero_sequencial:
      pos: [184,191]
      picture: '9(8)'
    data_gravacao:
      pos: [192,199]
      picture: '9(8)'
    data_credito:
      pos: [200,207]
      picture: '9(8)'
    brancos_06:
      pos: [208,240]
      picture: 'X(33)'
      default: ''

  trailer_lote:
    codigo_banco:
      pos: [1,3]
      picture: '9(3)'
      default: 341
    lote_servico:
      pos: [4,7]
      picture: '9(4)'
    tipo_registro:
      pos: [8,8]
      picture: '9(1)'
      default: 5
    brancos_01:
      pos: [9,17]
      picture: 'X(9)'
      default: ''
    quantidade_registros_lote:
      pos: [18,23]
      picture: '9(6)'
    quantidade_cobranca_simples:
      pos: [24,29]
      picture: '9(6)'
    valor_total_cobranca_simples:
      pos: [30,46]
      picture: '9(15)V9(2)'
    quantidade_cobranca_vinculada:
      pos: [47,52]
      picture: '9(6)'
    valor_total_cobranca_vinculada:
      pos: [53,69]
      picture: '9(15)V9(2)'
    zeros_01:
      pos: [70,115]
      picture: '9(46)'
      default: '0'

  trailer_arquivo:
    codigo_banco:
      pos: [1,3]
      picture: '9(3)'
      default: 341
    lote_servico:
      pos: [4,7]
      picture: '9(4)'
      default: 9999
    registro:
      pos: [8,8]
      picture: '9(1)'
      default: 9
    brancos_01:
      pos: [9,17]
      picture: 'X(9)'
      default: ''
    total_lotes:
      pos: [18,23]
      picture: '9(6)'
    total_registros:
      pos: [24,29]
      picture: '9(6)'
    zeros_01:
      pos: [30,35]
      picture: '9(6)'
      default: '000000'
    brancos_02:
      pos: [36,240]
      picture: 'X(205)'
      default: ''

  detalhes:
    segmento_p:
      codigo_banco:
        pos: [1,3]
        picture: '9(3)'
        default: 341
      lote_servico:
        pos: [4,7]
        picture: '9(4)'
      tipo_registro:
        pos: [8,8]
        picture: '9(1)'
        default: 1
      numero_sequencial_registro:
        pos: [9,13]
        picture: '9(5)'
      segmento:
        pos: [14,14]
        picture: 'X(1)'
        default: 'P'
      brancos_01:
        pos: [15,15]
        picture: 'X(1)'
        default: ''
      codigo_ocorrencia:
        pos: [16,17]
        picture: '9(2)'
      zeros_01:
        pos: [18,18]
        picture: '9(1)'
        default: '0'
      agencia:
        pos: [19,22]
        picture: '9(4)'
      brancos_02:
        pos: [23,23]
        picture: 'X(1)'
        default: ''
      zeros_02:
        pos: [24,30]
        picture: '9(7)'
        default: '0000000'
      conta_semdigito:
        pos: [31,35]
        picture: '9(5)'
      brancos_03:
        pos: [36,36]
        picture: 'X(1)'
        default: ''
      conta_digito:
        pos: [37,37]
        picture: '9(1)'
      carteira:
        pos: [38,40]
        picture: '9(3)'
      numero_documento:
        pos: [41,48]
        picture: '9(8)'
      brancos_04:
        pos: [49,57]
        picture: 'X(9)'
        default: ''
      zeros_03:
        pos: [58,62]
        picture: '9(5)'
        default: '00000'
      numero_documento_01:
        pos: [63,72]
        picture: '9(10)'
      brancos_05:
        pos: [73,77]
        picture: 'X(5)'
        default: ''
      vencimento:
        pos: [78,85]
        picture: '9(8)'
      valor_titulo:
        pos: [86,100]
        picture: '9(13)V9(2)'
      agencia_cobradora:
        pos: [101,105]
        picture: '9(5)'
        default: '00000'
      dac_agencia_cobradora:
        pos: [106,106]
        picture: '9(1)'
        default: '00000'
      especie:
        pos: [107,108]
        picture: '9(2)'
        default: '08'
      aceite:
        pos: [109,109]
        picture: 'X(1)'
        default: 'N'
      data_emissao:
        pos: [110,117]
        picture: '9(8)'
      zeros_04:
        pos: [118,118]
        picture: '9(1)'
        default: '0'
      data_juros_mora:
        pos: [119,126]
        picture: '9(8)'
      juros_1_dia:
        pos: [127,141]
        picture: '9(13)V9(2)'
      zeros_05:
        pos: [142,142]
        picture: '9(1)'
        default: '0'
      data_1o_desconto:
        pos: [143,150]
        picture: '9(8)'
      valor_1o_desconto:
        pos: [151,165]
        picture: '9(13)V9(2)'
      valor_iof:
        pos: [166,180]
        picture: '9(13)V9(2)'
      valor_abatimento:
        pos: [181,195]
        picture: '9(13)V9(2)'
      identificacao_titulo_empresa:
        pos: [196,220]
        picture: '9(23)'
        default: '0'
      codigo_negativacao_protesto:
        pos: [221,221]
        picture: '9(1)'
      prazo_negativacao_protesto:
        pos: [222,223]
        picture: '9(2)'
      codigo_baixa:
        pos: [224,224]
        picture: '9(1)'
      prazo_baixa:
        pos: [225,226]
        picture: '9(2)'
      zeros_06:
        pos: [227,240]
        picture: '9(15)'
        default: '0'

    segmento_q:
      codigo_banco:
        pos: [1,3]
        picture: '9(3)'
        default: 341
      lote_servico:
        pos: [4,7]
        picture: '9(4)'
      tipo_registro:
        pos: [8,8]
        picture: '9(1)'
        default: 1
      numero_sequencial_registro:
        pos: [9,13]
        picture: '9(5)'
      segmento:
        pos: [14,14]
        picture: 'X(1)'
        default: 'Q'
      brancos_01:
        pos: [15,15]
        picture: 'X(1)'
        default: ''
      codigo_ocorrencia:
        pos: [16,17]
        picture: '9(2)'
      tipo_inscricao:
        pos: [18,18]
        picture: '9(1)'
      inscricao_numero:
        pos: [19,33]
        picture: '9(15)'
      nome_pagador:
        pos: [34,63]
        picture: 'X(30)'
      brancos_02:
        pos: [64,73]
        picture: 'X(10)'
        default: ''
      logradouro:
        pos: [74,113]
        picture: 'X(40)'
      bairro:
        pos: [114,128]
        picture: 'X(15)'
      cep:
        pos: [129,136]
        picture: '9(8)'
      cidade:
        pos: [137,151]
        picture: 'X(15)'
      uf:
        pos: [152,153]
        picture: 'X(2)'
      sacador_tipo:
        pos: [154,154]
        picture: '9(1)'
      sacador_inscricao:
        pos: [155,169]
        picture: '9(15)'
      sacador_nome:
        pos: [170,199]
        picture: 'X(30)'
      brancos_03:
        pos: [200,209]
        picture: 'X(10)'
        default: ''
      zeros_01:
        pos: [210,212]
        picture: '9(3)'
        default: '000'
      brancos_04:
        pos: [213,240]
        picture: 'X(27)'
        default: ''
    segmento_r:
      codigo_banco:
        pos: [1,3]
        picture: '9(3)'
        default: 341
      lote_servico:
        pos: [4,7]
        picture: '9(4)'
      tipo_registro:
        pos: [8,8]
        picture: '9(1)'
        default: 1
      numero_sequencial_registro:
        pos: [9,13]
        picture: '9(5)'
      segmento:
        pos: [14,14]
        picture: 'X(1)'
        default: 'R'
      brancos_01:
        pos: [15,15]
        picture: 'X(1)'
        default: ''
      codigo_ocorrencia:
        pos: [16,17]
        picture: '9(2)'
      zeros_01:
        pos: [18,90]
        picture: '9(72)'
        default: '0'
      brancos_02:
        pos: [91,240]
        picture: 'X(150)'
        default: ''
