# FORMATO: BANCO DO BRASIL - FEBRABAN CNAB240
# OBJETIVO DO ARQUIVO: COBRANÇA BANCÁRIA
#
# TAMANHO DO REGISTRO
# O Tamanho do Registro é de 240 bytes.
#
# ALINHAMENTO DE CAMPOS
# - Campos Numéricos (9) = Sempre à direita e preenchidos com zeros à esquerda.
# - Campos Alfanuméricos (X) = Sempre à esquerda e preenchidos com brancos à direita. 
#
servico: 'cobranca'

versao: '087'

layout: 'cnab240'

retorno:

  header_arquivo:
    codigo_banco:
      pos: [1,3]
      picture: '9(3)'
      default: 1
    lote_servico:
      pos: [4,7]
      picture: '9(4)'
      default: '0000'
    tipo_registro:
      pos: [8,8]
      picture: '9(1)'
      default: '0'
    exclusivo_febraban_01:
      pos: [9,17]
      picture: 'X(9)'
      default: ''
    tipo_inscricao_empresa:
      pos: [18,18]
      picture: '9(1)'
    numero_inscricao_empresa:
      pos: [19,32]
      picture: '9(14)'
    numero_convenio:
      pos: [33,41]
      picture: '9(9)'
    cobranca_cedente:
      pos: [42,45]
      picture: '9(4)'
    numero_carteira_cobranca:
      pos: [46,47]
      picture: '9(2)'
    variacao_carteira_cobranca:
      pos: [48,50]
      picture: '9(3)'
    campo_reservado_bb:
      pos: [51,52]
      picture: 'X(2)'
    agencia_mantenedora_conta:
      pos: [53,57]
      picture: '9(5)'
    digito_verificador_agencia:
      pos: [58,58]
      picture: 'X(1)'
    numero_conta_corrente:
      pos: [59,70]
      picture: '9(12)'
    digito_verificador_conta:
      pos: [71,71]
      picture: 'X(1)'
    digito_verificador_agencia_conta:
      pos: [72,72]
      picture: 'X(1)'
    nome_empresa:
      pos: [73,102]
      picture: 'X(30)'
    nome_banco:
      pos: [103,132]
      picture: 'X(30)'
      default: 'BANCO DO BRASIL S.A.'
    exclusivo_febraban_02:
      pos: [133,142]
      picture: 'X(10)'
      default: ''
    codigo_remessa_retorno:
      pos: [143,143]
      picture: '9(1)'
    data_geracao_arquivo:
      pos: [144,151]
      picture: '9(8)'
    hora_geracao_arquivo:
      pos: [152,157]
      picture: '9(6)'
    numero_sequencial_arquivo:
      pos: [158,163]
      picture: '9(6)'
    versao_layout_arquivo:
      pos: [164,166]
      picture: '9(3)'
      default: '084'
    densidade_gravacao_arquivo:
      pos: [167,171]
      picture: '9(5)'
      default: 0
    reservado_banco_01:
      pos: [172,191]
      picture: 'X(20)'
      default: ''
    reservado_empresa_01:
      pos: [192,211]
      picture: 'X(20)'
      default: ''
    exclusivo_febraban_03:
      pos: [212,240]
      picture: 'X(29)'
      default: ''

  trailer_arquivo:
    codigo_banco:
      pos: [1,3]
      picture: '9(3)'
      default: 1
    lote_servico:
      pos: [4,7]
      picture: '9(4)'
      default: '9999'
    tipo_registro:
      pos: [8,8]
      picture: '9(1)'
      default: 9
    exclusivo_febraban_01:
      pos: [9,17]
      picture: 'X(9)'
      default: ''
    # Informar quantos lotes o arquivo possui.
    quantidade_lotes_arquivo:
      pos: [18,23]
      picture: '9(6)'
    # Quantidade igual ao número total de registros (linhas) do arquivo.
    quantidade_registros_arquivo:
      pos: [24,29]
      picture: '9(6)'
    quantidade_contas_conciliacao_lotes:
      pos: [30,35]
      picture: '9(6)'
      default: 0
    exclusivo_febraban_02:
      pos: [36,240]
      picture: 'X(205)'
      default: ''

  header_lote:
    codigo_banco:
      pos: [1,3]
      picture: '9(3)'
      default: 1
    lote_servico:
      pos: [4,7]
      picture: '9(4)'
    tipo_registro:
      pos: [8,8]
      picture: '9(1)'
      default: 1
    tipo_operacao:
      pos: [9,9]
      picture: 'X(1)'
      default: 'T'
    tipo_servico:
      pos: [10,11]
      picture: '9(2)'
      default: 1
    exclusivo_febraban_01:
      pos: [12,13]
      picture: 'X(2)'
      default: ''
    versao_layout_lote:
      pos: [14,16]
      picture: '9(3)'
      default: '043'
    exclusivo_febraban_02:
      pos: [17,17]
      picture: 'X(1)'
      default: ''
    tipo_inscricao_empresa:
      pos: [18,18]
      picture: '9(1)'
    numero_inscricao_empresa:
      pos: [19,33]
      picture: '9(14)'
    numero_convenio:
      pos: [34,42]
      picture: '9(9)'
    cobranca_cedente:
      pos: [43,46]
      picture: '9(4)'
    numero_carteira_cobranca:
      pos: [47, 48]
      picture: '9(2)'
    variacao_carteira_cobranca:
      pos: [49,51]
      picture: '9(3)'
    remessa_teste:
      pos: [52,53]
      picture: 'X(2)'
      default: ''
    agencia_mantenedora_conta:
      pos: [54,58]
      picture: '9(5)'
    digito_verificador_agencia:
      pos: [59,59]
      picture: 'X(1)'
    numero_conta_corrente:
      pos: [60,71]
      picture: '9(12)'
    digito_verificador_conta:
      pos: [72,72]
      picture: 'X(1)'
    digito_verificador_agencia_conta:
      pos: [73,73]
      picture: 'X(1)'
      default: ''
    nome_empresa:
      pos: [74,103]
      picture: 'X(30)'
    mensagem_01:
      pos: [104,143]
      picture: 'X(40)'
      default: ''
    mensagem_02:
      pos: [144,183]
      picture: 'X(40)'
      default: ''
    #Informação a cargo da empresa. Sugerimos informar número sequencial para controle. Campo não é criticado pelo Banco do Brasil.
    numero_remessa_retorno:
      pos: [184,191]
      picture: '9(8)'
    data_gravacao:
      pos: [192,199]
      picture: '9(8)'
      default: 0
    data_credito:
      pos: [200,207]
      picture: '9(8)'
      default: 0
    exclusivo_febraban_03:
      pos: [208,240]
      picture: 'X(33)'
      default: ''

  trailer_lote:
    codigo_banco:
      pos: [1,3]
      picture: '9(3)'
      default: 1
    lote_servico:
      pos: [4,7]
      picture: '9(4)'
    tipo_registro:
      pos: [8,8]
      picture: '9(1)'
      default: '5'
    exclusivo_febraban_01:
      pos: [9,17]
      picture: 'X(9)'
      default: ''
    # Total de linhas do lote (inclui Header de lote, Registros e Trailer de lote).
    quantidade_registros_lote:
      pos: [18,23]
      picture: '9(6)'
    exclusivo_febraban_02:
      pos: [24,240]
      picture: 'X(217)'
      default: ''

  detalhes:

    segmento_t:
      codigo_banco:
        pos: [1,3]
        picture: '9(3)'
        default: 1
      lote_servico:
        pos: [4,7]
        picture: '9(4)'
      tipo_registro:
        pos: [8,8]
        picture: '9(1)'
        default: 3
      numero_registro:
        pos: [9,13]
        picture: '9(5)'
      codigo_segmento:
        pos: [14,14]
        picture: 'X(1)'
        default: 'T'
      exclusivo_febraban_01:
        pos: [15,15]
        picture: 'X(1)'
        default: ''
      codigo_movimento:
        pos: [16,17]
        picture: '9(2)'
      agencia_mantenedora_conta:
        pos: [18,22]
        picture: '9(5)'
      verificador_agencia_mantenedora:
        pos: [23,23]
        picture: '9(1)'
      numero_conta:
        pos: [24,35]
        picture: '9(12)'
      verificador_conta:
        pos: [36,36]
        picture: '9(1)'
      verificador_agencia_conta:
        pos: [37,37]
        picture: '9(1)'
      identificacao_titulo:
        pos: [38,57]
        picture: 'X(20)'
      codigo_carteira:
        pos: [58,58]
        picture: '9(1)'
      numero_documento_cobranca:
        pos: [59,73]
        picture: 'X(15)'
        default: ''
      data_vencimento:
        pos: [74,81]
        picture: '9(8)'
      valor_nominal:
        pos: [82,96]
        picture: '9(13)V9(2)'
      numero_banco:
        pos: [97,99]
        picture: '9(3)'
      agencia_cobradora_recebedora:
        pos: [100,104]
        picture: '9(5)'
      verificador_agencia_cobradora_recebedora:
        pos: [105,105]
        picture: '9(1)'
      identificacao_titulo_empresa:
        pos: [106,130]
        picture: 'X(25)'
      codigo_moeda:
        pos: [131,132]
        picture: '9(2)'
        default: 9
      tipo_inscricao:
        pos: [133,133]
        picture: '9(1)'
      numero_inscricao:
        pos: [134,148]
        picture: '9(15)'
      nome:
        pos: [149,188]
        picture: 'X(40)'
      numero_contrato_operacao_credito:
        pos: [189,198]
        picture: '9(10)'
      valor_tarifa_custas:
        pos: [199,213]
        picture: '9(13)V9(2)'
      identificacao_rejeicoes:
        pos: [214,223]
        picture: 'X(10)'
      exclusivo_febraban_02:
        pos: [224,240]
        picture: 'X(17)'
        default: ''

    segmento_u:
      codigo_banco:
        pos: [1,3]
        picture: '9(3)'
        default: 1
      lote_servico:
        pos: [4,7]
        picture: '9(4)'
      tipo_registro:
        pos: [8,8]
        picture: '9(1)'
        default: 3
      numero_registro:
        pos: [9,13]
        picture: '9(5)'
      codigo_segmento:
        pos: [14,14]
        picture: 'X(1)'
        default: 'U'
      exclusivo_febraban_01:
        pos: [15,15]
        picture: 'X(1)'
        default: ''
      codigo_movimento:
        pos: [16,17]
        picture: '9(2)'
        default: ''
      juros_multa_encargos:
        pos: [18,32]
        picture: '9(13)V9(2)'
      valor_desconto_concedido:
        pos: [33,47]
        picture: '9(13)V9(2)'
      valor_abatimento_concedido:
        pos: [48,62]
        picture: '9(13)V9(2)'
      valor_iof:
        pos: [63,77]
        picture: '9(13)V9(2)'
      valor_pago:
        pos: [78,92]
        picture: '9(13)V9(2)'
      valor_liquido:
        pos: [93,107]
        picture: '9(13)V9(2)'
      outras_despesas:
        pos: [108,122]
        picture: '9(13)V9(2)'
      outros_creditos:
        pos: [123,137]
        picture: '9(13)V9(2)'
      data_ocorrencia:
        pos: [138,145]
        picture: '9(8)'
      data_efetivacao_credito:
        pos: [146,153]
        picture: '9(8)'
      codigo_ocorrencia:
        pos: [154,157]
        picture: '9(4)'
      data_ocorrencia_01:
        pos: [158,165]
        picture: '9(8)'
      valor_ocorrencia:
        pos: [166,180]
        picture: '9(13)V9(2)'
      complemento_ocorrencia:
        pos: [181,210]
        picture: 'X(30)'
      codigo_banco_correspondente_compensacao:
        pos: [211,213]
        picture: '9(3)'
      nosso_numero_banco_correspondente:
        pos: [214,233]
        picture: '9(20)'
      exclusivo_febraban_02:
        pos: [234,240]
        picture: 'X(7)'
        default: ''
